### PR TITLE
feat(south-modbus): Added option to choose which slave id to use duri…

### PR DESCRIPTION
**Pull request by Lulu300**
This is a feature that allows you to define a slave id during a modbus request. This is useful in case a Modbus gateway is used, thanks to this id the gateway will know which Modbus PLC to request.

### CODE REVIEW

**Comment by burgerni10** [comment]
Looks good to me for now. 

Don't forget to update the tests and the snapshots.

**Comment by Lulu300** [comment]
Je viens de les ajouter. Je continue le reste des modifications sur le module Modbus ici ou je fais une pull request par fonctionnalité ?

**Review by jfhenon — CHANGES_REQUESTED** [review]
src/south/Modbus/Modbus.class.spec.js#L90
Unexpected console statement

**Comment by burgerni10** [comment]
> I just added them. Should I continue the rest of the Modbus module modifications here or should I make a pull request by feature?

You can do several small pull requests like this one. This is easier for us to review.

While a PR is pending, you can go on with your work on separate branches. 

For example, you submit a PR from branch1 and you continue to add features on branche2 which is based on branch1.

We may request changes on branch1, so you go back to this on, commit your changes. Once the changes are approved, I will add those to the master branch (or main branch as we should say now). 
You may want to get these changes on your branch2. For this you need to update your local repository (`git fetch -p` and maybe `git pull`). Then you can rebase interactively your branch2 by doing `git rebase -i origin/master`. 
This is better than merge since it keeps a cleaner working tree. You can of course rebase your own work if you don't want to wait our review (from branch2 : `git rebase -i <your_fork>/branch1`).

If you submit a PR from branch2 while PR of branch1 still being active, please specify on your branch2 PR that this on is 'ON TOP OF #<PR_number>' so we can keep track of your work.

Let me know if you need any help with this method.

**Comment by burgerni10** [comment]
Once you take care of JF remarks, please check the file migration/migrationRules.js. This file is used to update the oibus.json config file when the settings of a connector changes.

It is the case for the Modbus connector settings, so you should increment the version (REQUIRED_SCHEMA_VERSION 21 -> 22 in migration.service.js) and add a json with the key '22' in the file migration/migrationRules.js. 

You can look at the previous migration step to do something similar : filter the modbus settings and update it by adding a default value for slaveId. 

For your next changes on settings, please don't forget to update this part again.

Be careful though : once you start OIBus, your config file will be at version 22. So instead of incrementing a lot of versions at once, downgrade manually the schemaVersion property in the file tests/oibus.json, improve your step 22 in migration rules, and start again OIBus to get your latest migration changes.

**Comment by burgerni10** [comment]
Last comment : I've created the branch modbus/develop to merge your pull requests regularly in this branch. Once it will be done, I'll merge it with master. So please base your next branch on modbus/develop

**Comment by Lulu300** [comment]
> 
> 
> src/south/Modbus/Modbus.class.spec.js#L90
> Unexpected console statement

Sorry I completely forgot to remove this line, I will remove it right away.

> 
> 
> > I just added them. Should I continue the rest of the Modbus module modifications here or should I make a pull request by feature?
> 
> You can do several small pull requests like this one. This is easier for us to review.
> 
> While a PR is pending, you can go on with your work on separate branches.
> 
> For example, you submit a PR from branch1 and you continue to add features on branche2 which is based on branch1.
> 
> We may request changes on branch1, so you go back to this on, commit your changes. Once the changes are approved, I will add those to the master branch (or main branch as we should say now).
> You may want to get these changes on your branch2. For this you need to update your local repository (`git fetch -p` and maybe `git pull`). Then you can rebase interactively your branch2 by doing `git rebase -i origin/master`.
> This is better than merge since it keeps a cleaner working tree. You can of course rebase your own work if you don't want to wait our review (from branch2 : `git rebase -i <your_fork>/branch1`).
> 
> If you submit a PR from branch2 while PR of branch1 still being active, please specify on your branch2 PR that this on is 'ON TOP OF #<PR_number>' so we can keep track of your work.
> 
> Let me know if you need any help with this method.

Yeah I think it'll be a lot easier to work that way.


> 
> 
> Once you take care of JF remarks, please check the file migration/migrationRules.js. This file is used to update the oibus.json config file when the settings of a connector changes.
> 
> It is the case for the Modbus connector settings, so you should increment the version (REQUIRED_SCHEMA_VERSION 21 -> 22 in migration.service.js) and add a json with the key '22' in the file migration/migrationRules.js.
> 
> You can look at the previous migration step to do something similar : filter the modbus settings and update it by adding a default value for slaveId.
> 
> For your next changes on settings, please don't forget to update this part again.
> 
> Be careful though : once you start OIBus, your config file will be at version 22. So instead of incrementing a lot of versions at once, downgrade manually the schemaVersion property in the file tests/oibus.json, improve your step 22 in migration rules, and start again OIBus to get your latest migration changes.

I'm going to make the changes, sorry I didn't do it earlier I didn't pay attention to this part




> 
> 
> Last comment : I've created the branch modbus/develop to merge your pull requests regularly in this branch. Once it will be done, I'll merge it with master. So please base your next branch on modbus/develop

No problem, as soon as I add the next feature I'll base my branch on modbus/develop

**Review by burgerni10 — APPROVED** [review]

**Comment by Lulu300** [comment]
Is there something else you want me to change or is it good for you ?

**Comment by burgerni10** [comment]
> Is there something else you want me to change or is it good for you ?

I was waiting for JF review, but it's ok for the slaveId part. Thank you !
You can go on from the branch modbus/develop

**Pull request merged**
