### PR TITLE
Remove listen#964

### PR DESCRIPTION
**Pull request by attilasuto**
ScanMode should not offer the mode "listen" anymore as it is automatically created #964

### CODE REVIEW

**Review by jfhenon — CHANGES_REQUESTED** [review]
This needs a "migration" of the json on the backend.

**Comment by burgerni10** [comment]
Before managing the migration, please rebase (and not merge) your branch to be up to date with the repo.

**Comment by jfhenon** [comment]
need branch rebase and then write a migration to remove "listen" scanMode in it exists in oibus.json

**Comment by burgerni10** [comment]
@attilasuto I made the rebase. Your branch is now up to date with master, you can work on the migration :)

**Comment by jfhenon** [comment]
> @attilasuto I made the rebase. Your branch is now up to date with master, you can work on the migration :)

thankqs @burgerni10. The migration is done on the backend by @kukukk

**Comment by kukukk** [comment]
After some further discussion we need to:
1. keep the scanModes setting as it is now. We don't need listen to be defined.
2. keep the South point config as it is when listen is not supported (Modbus) - because it is not in the scanModes list, it won't apear
3. hard-code for MQTT the listen scanMode instead of showing the real scanModes list
4. we can keep the check in the Engine, but it won't do anything because if the listen scanMode is not in the scanModes list, it will be ignored.
5. the migration needs only to remove the listen scanMode from the scanModes list, but do not touch the points section.

Step 3) still needs to be implemented on frontend and step 5) on backend.

**Review by jfhenon — APPROVED** [review]

**Pull request merged**
