### PR TITLE
North watsy connect

### PR DESCRIPTION
**Pull request by victor-tndl**
Creation of a WATSYConnect North connector. This connector allows OIBUS to send MQTT message into WATSY format. The handle's values are process with a splitTimeout logic in order not to send one message but a batch of messages.

### CODE REVIEW

**Comment by burgerni10** [comment]
Please rebase (and not merge) your branch before resubmitting this PR.

**Comment by victor-tndl** [comment]
I can't rebase my branch. There are over 1500 commits/conflicts to fix. Moreover doing this thanks to gitkraken, my computer is running over 150% of his CPU.

**Comment by burgerni10** [comment]
> I can't rebase my branch. There are over 1500 commits/conflicts to fix. Moreover doing this thanks to gitkraken, my computer is running over 150% of his CPU.

I rebase it on my local machine since it needed a refactor of the testConfig.js. FYI, here is how I did it : 
`git fetch -a
git checkout North_WATSY_connect
git rebase -i origin/master`

At this point, I selected only your commits to be kept on the new rebase, and I had only two conflicts (on the testConfig.js and another on the API.jsx) which I resolved. Then I went on with the rebase :

`git rebase --continue`

I tested everything with jest and adapted the decryption method which change a bit since your commits. The tests work fine but can you check everything works fine on your side ? To bring the changes on your machine, you can git fetch and git pull the repo, but if you have any problems, just reclone the project.

Be careful when starting the project from scratch : you may need to change on the oibus.json file the safeMode true to false (this is an issue currently being fixed, already referenced #972 ) 

Please, let me know how it goes.

**Comment by victor-tndl** [comment]
It seems to be good for us!

**Review by jfhenon — APPROVED** [review]

**Pull request merged**
