### PR TITLE
paginated-logs-backend

### PR DESCRIPTION
**Pull request by burgerni10**
Prepare paginate logs #1809 on the backend

The filtering for text content is now possible on the backend. It was previously done on the client side with all logs.

Still to implement by @Reloflex: 
- A pagination component to navigate between page
- A form as shown in #1809
- A rework of the displayed logs
- A hint that now logs match the query if no log is retrieved

### CODE REVIEW

**Review by jfhenon — COMMENTED** [review]
do we still need getLogs() and, if yes, should this call getPaginatedLogs behind the scene?

**Comment by burgerni10** [comment]
> do we still need getLogs() and, if yes, should this call getPaginatedLogs behind the scene?

Yes getLogs is still used. We cannot remove it without refactoring the whole log page (form, results querying). I suggest to remove it once the rest of the work will be done.

**Review by marouanehassanioptimistik — CHANGES_REQUESTED** [review]
i think the sorting should be passed as a parameter. also it is more logic to sort logs by timestamp descending by default

**Comment by burgerni10** [comment]
> i think the sorting should be passed as a parameter. also it is more logic to sort logs by timestamp descending by default



> i think the sorting should be passed as a parameter. also it is more logic to sort logs by timestamp descending by default

My mistake, it should indeed be descending.

However, I don't think it makes sense to have a sorting parameter: I don't see a use case where we would like to go through the logs from the start.

**Comment by marouanehassanioptimistik** [comment]
it seems best practice to me for a database service not to suppose what the use is for it is at least more flexible. We don't necessarily need to allow another sorting at ui level and it is up to the rest controller to hard code the sorting. Just à thought you can hardcode the sorting in the service if you judge it is overkill design.

**Pull request merged**
